language: ruby
rvm:
- 2.5.1
before_install:
- gem install bundler
before_script:
- cp config/database.yml.ci config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  secure: "U5vWStcSEQG0AtqhpH+52bGhitQm0+ci0GRzmtaWAsYWCG0imNkVZhiAHylm8j5P9tXQka/GDSn/97UiVYBOjBZUGkIxuRHvkWzQ2KOiesGGZnMSffVdRl5K1+iitaTG5VWPY0VWz6uY5j1Lr3WbDeXM3mv0UF0uSgK/Yj8VVT47kdD8ASpO69zLAMSHKrJgWl20/obfCOZSqSjkDSHglXzC55NDY3nF8aMp7QgZhMKTCCCjDBtA9TglKeD5iAxbfbF0J/Wi7dMqgRMyaQWgHNpVz/pGxHSG44IUG1I3CWu62VdVncRhkRfRys+Kk5Ldtr/3taMFhGd6lMybSdpU58yQ42x98kugovQJ1paaT2IEQyndWh43c1Nw9qMtVCswrPWlC+uIlT1VB8e34fxzyj7WsbvQOfnBF0R8P6bUeFK19UOlF9aeJRjFT+tiDw9Zrii3nPu/keQkZH8e91s0QM3W2jSGpHkqERwu82f55weIkSUBQlqAAhdTEf2QurU+ziLe8ujaUPIn3+FXwWvppAIhHpKENLSywIwaeiV5zKuINg6qXS+4pX8vx/v0ba53DYquyg9biK4s07xn8V989qb7s1ygh5A+KpZz0Akvu4uaA7d83fgrPMvRiEeGR4QcOGMjuQmq6A9FORzA4SwMmvM5229DU3O0Jb3qeveVcwk="
  app: polar-inlet-31293
  on:
    repo: katguz3485/LabManager
