default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: lab-manager_development

test:
  <<: *default
  database: lab-manager_test

production:
  <<: *default
  database: lab-manager_production
  username: lab-manager
  password: <%= ENV['LAB-MANAGER_DATABASE_PASSWORD'] %>

